.catalog:
  name: ELB Classic Load Balancer
  version: "v0.1"
  description: "Clean up terminated AWS hosts"
    - variable: "AWS_ACCESS_KEY_ID"
      label: "AWS Access Key ID"
      description: "Access key ID for your AWS account (Will use EC2 Role if unset)"
      type: "string"
      required: false
    - variable: "AWS_SECRET_ACCESS_KEY"
      label: "AWS Secret Access Key"
      description: "Secret access key for your AWS account (Will use EC2 Role if unset)"
      type: "string"
      required: false
      
aws-reaper:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2