name: Custom
description: Default Cattle template
stacks:
  - name: network-services
    templateId: 'library:infra*network-services'
  - name: ipsec
    templateId: 'library:infra*ipsec'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
  - name: elb-service
    templateId: 'custom:infra*aws-elbv1'
  - name: reaper-service
    templateId: 'custom:infra*aws-reaper'